### ISSUE TITLE
Configurable throttle

### ISSUE THREAD

**Issue by ezoSresyeK** [emagaliff/znc-nicktrace#2]
This module in lots of cases causes Excess Floods (was not flooding before module load). I was wondering if a configurable throttle variable obeyed for issuing IRC commands would be a good idea. Otherwise... it is possible that python modules obey ZNC's config options for throttling lines per second with burst rates and I'm simply ignorant and likely have tweaked the config for such to something a tad faster though permitting excess floods upon the load of this module.

Another thing I've noticed is it sends a /who per join. I'm not sure it should even do this actually. It could catch join events and get nick/ident/host info from said instead (as I believe that's all the /who actually gets it). This would definitely cut out 80% of excess flood cases.

Outside of this, great work, am fairly impressed with this mod's thoroughness and features. Thanks for a very useful addition for ZNC.

**Comment by KindOne-** [comment]
So enable flood protection in ZNC.

**Comment by ezoSresyeK** [comment]
The question being however, do modules even obey ZNC flood protection or is that up to the module writer. I have yet to delve into ZNC sources to check this and having not written modules was hoping it might be easier asked than to spend hours looking quite possibly.

The other question is, this sends a /who per join, however, upon join, the information found in a /who is also found in the /join (for the most part, it could be that there is other information that is utilized by the module that a /who presents whereas a join event does not).

I am by no means an expert and hope picking your brain in this issue is not an issue. I am simply learning as I go along.

**Comment by necessary129** [comment]
@ezoSresyeK aka does not send a `/who` on join of every user, the `PROCESS_CHANNEL_ON_JOIN`  configuration variable is for processing channels that you join, like, sending a `/who` when you join a channel.

**Comment by necessary129** [comment]
@ezoSresyeK Check if `PROCESS_CHANNELS_ON_LOAD` and `PROCESS_CHANNEL_ON_JOIN` conf variables are enabled, if they are, disable them for the time being until it is fixed, It should stop the excess floods.

**Comment by KindOne-** [comment]
```The question being however, do modules even obey ZNC flood protection``` Yes.

You can always ask questions about znc in ```#znc``` / ```#znc-dev``` on freenode to try to get a faster responce.

**Comment by emagaliff** [comment]
Sorry for the long reply. @ezoSresyeK WHO on join is now removed as it gets all the user info from the JOIN.
