### ISSUE TITLE
Line 51, comma missing, syntax error

### ISSUE THREAD

**Issue by ezoSresyeK** [emagaliff/znc-nicktrace#3]
[https://github.com/emagaliff/znc-nicktrace/blob/master/aka.py#L50](Syntax error here.)

Feel lame pointing out such a small issue, but noticed it while processing the update on the znc's via the module's update command and subsequent "PRIVMSG *status :updatemod aka".  It's already fixed on my znc's. If there is a more preferred way of referencing something like this let me know.

**Comment by emagaliff** [comment]
@ezoSresyeK What are you referencing? The link is to the line with the `WHO_USER_ON_JOIN` config variable.

**Comment by ezoSresyeK** [comment]
Missing comma at end of line
